pipeline{
    agent any
    stages{
        stage('Build MVN'){
            steps{
                echo 'Build Maven Project'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing..'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploy Project'
            }
        }
    }
}