pipeline{
    agent any
    stages{
        stage('Build MVN'){
            steps{
                echo 'Build Maven Project'
                sh 'cd jenkins-demo && mvn -B -DskipTests clean package'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing..'
                sh 'cd jenkins-demo && mvn test'
            }
        }
        stage('Deploy'){
            steps{
                sh "echo Deploying Project ${env.HOME}"
                dir("/jenkins-demo/src/main/resources"){
                sh "ls"
                script{
                    docker.build("jenkins-demo:latest")
                }
               }
            }
        }
    }
}